//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IT_Admin {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IT_Admin.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persist Security Info=False;server=192.168.168.91;Database=ATECApi;User ID=atecapiuser;Password=atecapi!234;Connection Timeout=240;TrustServerCertificate=true.
        /// </summary>
        internal static string DevAtecApiConnectionString {
            get {
                return ResourceManager.GetString("DevAtecApiConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persist Security Info=False;server=192.168.168.91;Database=ATECApiData;User ID=atecapiuser;Password=atecapi!234;Connection Timeout=240;TrustServerCertificate=true.
        /// </summary>
        internal static string DevAtecApiDataConnectionString {
            get {
                return ResourceManager.GetString("DevAtecApiDataConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persist Security Info=False;server=192.168.168.69;Database=ATECorp_Kentico;User ID=Kentico;Password=K1923j4zu8;Connection Timeout=240;TrustServerCertificate=true.
        /// </summary>
        internal static string DevKentico {
            get {
                return ResourceManager.GetString("DevKentico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persist Security Info=False;server=74.62.189.23;Database=ATECApi;User ID=atecapiuser;Password=atecapi!234;Connection Timeout=240;TrustServerCertificate=true.
        /// </summary>
        internal static string LiveAtecApiConnectionString {
            get {
                return ResourceManager.GetString("LiveAtecApiConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persist Security Info=False;server=74.62.189.23;Database=ATECApiData;User ID=atecapiuser;Password=atecapi!234;Connection Timeout=240;TrustServerCertificate=true.
        /// </summary>
        internal static string LiveAtecApiDataConnectionString {
            get {
                return ResourceManager.GetString("LiveAtecApiDataConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persist Security Info=False;server=74.62.189.23;Database=ATECorp_Kentico;User ID=Kentico;Password=K1923j4zu8;Connection Timeout=240;TrustServerCertificate=true.
        /// </summary>
        internal static string LiveKentico {
            get {
                return ResourceManager.GetString("LiveKentico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persist Security Info=False;server=74.62.189.23;Database=ATECCS;User ID=Kentico;Password=K1923j4zu8;Connection Timeout=240;TrustServerCertificate=true.
        /// </summary>
        internal static string StagingKentico {
            get {
                return ResourceManager.GetString("StagingKentico", resourceCulture);
            }
        }
    }
}
